### ISSUE TITLE
Brazilian characters broking TwiML method

### ISSUE THREAD

**Issue by cronemberger** [twilio/twilio-aspnet#12]
It seems that every time that I have some Brazilian characters and words, like for example "não" which means "no", the static method LoadFromString which returns a XDocument, gets a non expected Exception.

Path:
TwilioController->TwiML(MessagingResponse response)->TwiMLResult->LoadFromString(xx)

**Comment by philnash** [comment]
`LoadFromString` uses `Encoding.Default` by default. I imagine that "não" requires `Encoding.UTF8` instead. `TwiML`, `TwiMLResult` and `LoadFromString` all have overloads that take an encoding as the second argument. I'm not sure exactly how it all fits together in your app, but if you could pass the encoding at some point, then this should stop crashing.

**Comment by HGSandhagen** [comment]
Same with german characters (ä,ö,ü etc.). @philnash : Your solution (setting the encoding explicit) works, but both packages twillio and twillio-aspnet are inconstistent. The ToXml method of TwiML uses always UTF-8 Encoding, TwlMLResult.LoadFromString uses Encoding.Default. So most of the example code does not work with foreign characters:
```
public TwiMLResult Index(VoiceRequest request)
        {
            var response = new VoiceResponse();
            response.Say($"Welcome. Are you from {request.FromCity}?");
            return TwiMLResult(response);
        }
```

**Comment by philnash** [comment]
Thanks for pointing this out @HGSandhagen. I will raise with the team and see if we can bring this around to some sort of consistency.

**Comment by dprothero** [comment]
Yep, UTF8 is the more logical default. I will make that change.
