### ISSUE TITLE
Request class for sms statusCallback

### ISSUE THREAD

**Issue by rossiter10** [twilio/twilio-aspnet#16]
Is there a specific class we can use for the sms status callbacks? I see `StatusCallbackRequest`, but it inherits from `VoiceRequest`. Can we get something like an `SmsStatusCallbackRequest` that we can use instead of checking `Request.Form`?

So specifically, I'm talking about the webhook outlined here for when you want the get the updated status of a message:
https://www.twilio.com/docs/sms/tutorials/how-to-confirm-delivery-csharp

**Comment by dprothero** [comment]
Good idea @rossiter10, I will look at adding this.

**Comment by dprothero** [comment]
Done! Just uploaded 5.20.1 to Nuget.
