### ISSUE TITLE
TwiMLResult doesn't work with custom encoding

### ISSUE THREAD

**Issue by MichaelSL** [twilio/twilio-aspnet#2]
I try to use the programmable voice for Swedish language and the callback fails with exception.
It is happens because the server locale is `en-us` and `Encoding.Default` returns `ASCII`. I need a `UTF8` for my case.
Default encoding is hard coded in `Twilio.AspNet.Mvc.TwiMLResult.LoadFromString`.

My proposal is to add an overloaded version with encoding parameter.

The current workaround is to subclass from the `TwiMLResult` and add the missing method.

**Comment by MichaelSL** [comment]
Created a [pull request](https://github.com/twilio/twilio-aspnet/pull/3) that can resolve the issue.

**Comment by dprothero** [comment]
@MichaelSL PR accepted!
