### ISSUE TITLE
Dependency on .NET Standard 1.6.1

### ISSUE THREAD

**Issue by KFayal** [twilio/twilio-aspnet#7]
I was trying to utilize the Twilio.ASPNet.Core library in my Lambda function, but when I went to publish it to Lambda, I was informed that it has a dependency on .NET Standard 1.6.1, and the max version supported by netcoreapp 1.0 is 1.6.0.  Lambda only supports .NET Core 1.0, which is what this library says is the lowest version it supports.  Is there a trick in the .csproj file or something I can do to make this only use .NET Standard 1.6.0?

**Comment by KFayal** [comment]
You can mark this as closed.  I used the Twilio REST API helper library 5.8.2.  Couldn't go any higher simply because of the later versions reference .net standard 1.6.1

**Comment by dprothero** [comment]
I can definitely see how this would be extremely frustrating. Now that AWS Lambda supports .NET Core 2.0, I am closing this issue:
https://aws.amazon.com/about-aws/whats-new/2018/01/aws-lambda-supports-c-sharp-dot-net-core-2-0/
